using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;

namespace Tritone.Editor.CodeGeneration
{
    /// <summary>
    /// Generates typed messages, codecs, request relationships, and registration code.
    /// </summary>
    internal static class NetworkCodeGenerator
    {
        private const string SchemaPath = "Assets/Tritone/Network.json";
        private const string DefaultOutputPath = "Assets/Generated/Tritone/Network";

        // Maps schema field types to allocation-conscious binary codec operations.
        private static readonly Dictionary<string, CodecMethod> sCodecMethods = new()
        {
            { "bool", new CodecMethod("WriteBoolean", "ReadBoolean") },
            { "byte[]", new CodecMethod("WriteBytes", "ReadBytes") },
            { "float", new CodecMethod("WriteSingle", "ReadSingle") },
            { "int", new CodecMethod("WriteInt32", "ReadInt32") },
            { "string", new CodecMethod("WriteString", "ReadString") }
        };

        [MenuItem("Tritone/Generate/Network Messages")]
        internal static void Generate()
        {
            var schema  = GenerationUtility.ReadSchema<NetworkSchema>(SchemaPath);
            var changed = Generate(schema);
            if (changed)
                AssetDatabase.Refresh();
        }

        internal static bool Generate(NetworkSchema schema)
        {
            Validate(schema);
            var outputPath = string.IsNullOrWhiteSpace(schema.OutputPath)
                ? DefaultOutputPath
                : schema.OutputPath;
            var expectedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var changed       = false;
            for (int i = 0, cnt = schema.Messages.Length; i < cnt; i++)
            {
                var message = schema.Messages[i];
                var path    = Path.Combine(outputPath, message.Name + "Message.Generated.cs");
                expectedFiles.Add(Path.GetFullPath(path));
                changed |= GeneratedFileWriter.WriteIfChanged(
                    path,
                    BuildMessage(schema.Namespace, message));
            }
            var registryPath = Path.Combine(outputPath, "NetworkMessages.Generated.cs");
            expectedFiles.Add(Path.GetFullPath(registryPath));
            changed |= GeneratedFileWriter.WriteIfChanged(
                registryPath,
                BuildRegistry(schema.Namespace, schema.Messages));
            changed |= RemoveStaleFiles(outputPath, expectedFiles);
            return changed;
        }

        private static string BuildMessage(string namespaceName,
                                           NetworkMessageDefinition message)
        {
            var isRequest  = IsKind(message, "Request");
            var isResponse = IsKind(message, "Response");
            var contract   = isRequest
                ? $" : INetworkRequest<{message.Response}>"
                : isResponse
                    ? " : INetworkResponse"
                    : "";
            CodeTextBuilder code = new();
            code.Line("// <auto-generated />");
            code.Line("using Tritone.Messaging;");
            code.Line("using Tritone.Networking;");
            code.Line();
            code.Open($"namespace {namespaceName}");
            code.Line("/// <summary>");
            code.Line($"/// Defines the generated {message.Name} network message.");
            code.Line("/// </summary>");
            code.Open($"public sealed class {message.Name}{contract}");
            if (isRequest || isResponse)
            {
                code.Line("/// <summary>");
                code.Line("/// Gets or sets the correlated request identifier.");
                code.Line("/// </summary>");
                code.Line("public int RequestId { get; set; }");
                if (message.Fields.Length > 0)
                    code.Line();
            }
            for (int i = 0, cnt = message.Fields.Length; i < cnt; i++)
            {
                var field = message.Fields[i];
                code.Line($"// Stores the {field.Name} message value.");
                code.Line($"public {field.Type} {field.Name};");
                if (i < cnt - 1)
                    code.Line();
            }
            code.Close();
            code.Line();
            code.Line("/// <summary>");
            code.Line($"/// Encodes and decodes {message.Name} without reflection.");
            code.Line("/// </summary>");
            code.Open($"public sealed class {message.Name}Codec : IMessageCodec<{message.Name}>");
            code.Line("/// <inheritdoc />");
            code.Open($"public void Write(MessageWriter writer, {message.Name} message)");
            if (isRequest || isResponse)
                code.Line("writer.WriteInt32(message.RequestId);");
            for (int i = 0, cnt = message.Fields.Length; i < cnt; i++)
            {
                var field = message.Fields[i];
                code.Line($"writer.{sCodecMethods[field.Type].Write}(message.{field.Name});");
            }
            code.Close();
            code.Line();
            code.Line("/// <inheritdoc />");
            code.Open($"public {message.Name} Read(MessageReader reader)");
            code.Line($"return new {message.Name}");
            code.Line("{");
            var valueCount = message.Fields.Length + (isRequest || isResponse ? 1 : 0);
            var valueIndex = 0;
            if (isRequest || isResponse)
            {
                valueIndex++;
                code.Line($"    RequestId = reader.ReadInt32(){Comma(valueIndex, valueCount)}");
            }
            for (int i = 0, cnt = message.Fields.Length; i < cnt; i++)
            {
                var field = message.Fields[i];
                valueIndex++;
                code.Line(
                    $"    {field.Name} = reader.{sCodecMethods[field.Type].Read}(){Comma(valueIndex, valueCount)}");
            }
            code.Line("};");
            code.Close();
            code.Close();
            code.Close();
            return code.ToString();
        }

        private static string BuildRegistry(string namespaceName,
                                            NetworkMessageDefinition[] messages)
        {
            CodeTextBuilder code = new();
            code.Line("// <auto-generated />");
            code.Line("using Tritone.Messaging;");
            code.Line();
            code.Open($"namespace {namespaceName}");
            code.Line("/// <summary>");
            code.Line("/// Registers every generated message codec and stable type identifier.");
            code.Line("/// </summary>");
            code.Open("public static class NetworkMessages");
            for (int i = 0, cnt = messages.Length; i < cnt; i++)
            {
                code.Line($"// Stores the stable {messages[i].Name} wire identifier.");
                code.Line($"public const int {messages[i].Name}Id = {messages[i].Id};");
            }
            code.Line();
            code.Line("/// <summary>");
            code.Line("/// Registers all generated codecs with one serializer.");
            code.Line("/// </summary>");
            code.Open("public static void Register(IMessageSerializer serializer)");
            code.Line("if (serializer == null)");
            code.Line("    throw new System.ArgumentNullException(nameof(serializer));");
            for (int i = 0, cnt = messages.Length; i < cnt; i++)
            {
                var message = messages[i];
                code.Line(
                    $"serializer.Register({message.Name}Id, new {message.Name}Codec());");
            }
            code.Close();
            code.Close();
            code.Close();
            return code.ToString();
        }

        private static void Validate(NetworkSchema schema)
        {
            if (schema == null)
                throw new ArgumentNullException(nameof(schema));
            GenerationUtility.ValidateNamespace(schema.Namespace, "Network namespace");
            if (schema.Messages == null || schema.Messages.Length == 0)
                throw new InvalidDataException("At least one network message is required.");

            HashSet<int> ids      = new();
            HashSet<string> names = new(StringComparer.Ordinal);
            Dictionary<string, NetworkMessageDefinition> byName = new(StringComparer.Ordinal);
            for (int i = 0, cnt = schema.Messages.Length; i < cnt; i++)
            {
                var message = schema.Messages[i] ??
                              throw new InvalidDataException($"Network message {i} is null.");
                GenerationUtility.ValidateIdentifier(message.Name, "Network message");
                if (message.Id <= 0 || !ids.Add(message.Id))
                    throw new InvalidDataException(
                        $"Network message '{message.Name}' has an invalid or duplicate ID.");
                if (!names.Add(message.Name))
                    throw new InvalidDataException(
                        $"Network message '{message.Name}' is defined more than once.");
                if (!string.IsNullOrEmpty(message.Kind) &&
                    !IsKind(message, "Request") &&
                    !IsKind(message, "Response") &&
                    !IsKind(message, "Message"))
                    throw new InvalidDataException(
                        $"Network message '{message.Name}' has unsupported kind '{message.Kind}'.");
                message.Fields ??= Array.Empty<NetworkFieldDefinition>();
                ValidateFields(message);
                byName.Add(message.Name, message);
            }
            for (int i = 0, cnt = schema.Messages.Length; i < cnt; i++)
            {
                var request = schema.Messages[i];
                if (!IsKind(request, "Request"))
                    continue;
                if (string.IsNullOrEmpty(request.Response) ||
                    !byName.TryGetValue(request.Response, out var response) ||
                    !IsKind(response, "Response"))
                    throw new InvalidDataException(
                        $"Request '{request.Name}' must reference a generated response message.");
            }
        }

        private static void ValidateFields(NetworkMessageDefinition message)
        {
            HashSet<string> fields = new(StringComparer.Ordinal);
            for (int i = 0, cnt = message.Fields.Length; i < cnt; i++)
            {
                var field = message.Fields[i] ??
                            throw new InvalidDataException(
                                $"Message '{message.Name}' field {i} is null.");
                GenerationUtility.ValidateIdentifier(field.Name, "Network field");
                if (field.Name == "RequestId" || !fields.Add(field.Name))
                    throw new InvalidDataException(
                        $"Message '{message.Name}' field '{field.Name}' is reserved or duplicated.");
                if (!sCodecMethods.ContainsKey(field.Type))
                    throw new InvalidDataException(
                        $"Message '{message.Name}' field '{field.Name}' uses unsupported type '{field.Type}'.");
            }
        }

        private static bool IsKind(NetworkMessageDefinition message, string kind)
        {
            return string.Equals(message.Kind, kind, StringComparison.OrdinalIgnoreCase);
        }

        private static string Comma(int index, int count)
        {
            return index < count ? "," : "";
        }

        private static bool RemoveStaleFiles(string outputPath,
                                             HashSet<string> expectedFiles)
        {
            if (!Directory.Exists(outputPath))
                return false;
            var changed = false;
            var files   = Directory.GetFiles(outputPath, "*Message*.Generated.cs");
            for (int i = 0, cnt = files.Length; i < cnt; i++)
            {
                if (expectedFiles.Contains(Path.GetFullPath(files[i])))
                    continue;
                File.Delete(files[i]);
                var metaPath = files[i] + ".meta";
                if (File.Exists(metaPath))
                    File.Delete(metaPath);
                changed = true;
            }
            return changed;
        }

        private readonly struct CodecMethod
        {
            internal string Write { get; }
            internal string Read { get; }

            internal CodecMethod(string write, string read)
            {
                Write = write;
                Read  = read;
            }
        }
    }
}
