using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;

namespace Tritone.Editor.CodeGeneration
{
    /// <summary>
    /// Generates Unity-serializable table rows and stable table descriptors.
    /// </summary>
    internal static class TableCodeGenerator
    {
        private const string SchemaPath = "Assets/Tritone/Tables.json";
        private const string DefaultOutputPath = "Assets/Generated/Tritone/Tables";

        // Limits schemas to types handled predictably by Unity JSON.
        private static readonly HashSet<string> sSupportedTypes = new()
        {
            "bool",
            "double",
            "float",
            "int",
            "long",
            "string"
        };

        /// <summary>
        /// Generates every configured table from the conventional project schema.
        /// </summary>
        [MenuItem("Tritone/Generate/Tables")]
        internal static void Generate()
        {
            var schema = GenerationUtility.ReadSchema<TableSchema>(SchemaPath);
            var changed = Generate(schema);
            if (changed)
                AssetDatabase.Refresh();
        }

        /// <summary>
        /// Generates every table from one parsed schema.
        /// </summary>
        /// <param name="schema">The validated table schema root.</param>
        /// <returns>True when any generated file changed.</returns>
        internal static bool Generate(TableSchema schema)
        {
            Validate(schema);
            var outputPath = string.IsNullOrWhiteSpace(schema.OutputPath)
                ? DefaultOutputPath
                : schema.OutputPath;
            var changed = false;
            var expectedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            for (int i = 0, cnt = schema.Tables.Length; i < cnt; i++)
            {
                var table = schema.Tables[i];
                var path  = Path.Combine(outputPath, table.Name + "Table.Generated.cs");
                expectedFiles.Add(Path.GetFullPath(path));
                changed |= GeneratedFileWriter.WriteIfChanged(path, Build(schema.Namespace, table));
            }
            changed |= RemoveStaleFiles(outputPath, expectedFiles);
            return changed;
        }

        /// <summary>
        /// Builds one complete generated table source file.
        /// </summary>
        private static string Build(string namespaceName, TableDefinition table)
        {
            var keyField = GetKeyField(table);
            CodeTextBuilder code = new();
            code.Line("// <auto-generated />");
            code.Line("using System;");
            code.Line("using Tritone.Tables;");
            code.Line();
            code.Open($"namespace {namespaceName}");
            code.Line("/// <summary>");
            code.Line($"/// Stores one row from the {table.Name} configuration table.");
            code.Line("/// </summary>");
            code.Line("[Serializable]");
            code.Open($"public sealed class {table.Name}Row : ITableRow<{keyField.Type}>");
            for (int i = 0, cnt = table.Fields.Length; i < cnt; i++)
            {
                var field = table.Fields[i];
                code.Line($"// Stores the {field.Name} configuration value.");
                code.Line($"public {field.Type} {field.Name};");
                code.Line();
            }
            code.Line("/// <summary>");
            code.Line("/// Gets the stable row key.");
            code.Line("/// </summary>");
            code.Line($"public {keyField.Type} Key => {keyField.Name};");
            code.Close();
            code.Line();
            code.Line("/// <summary>");
            code.Line($"/// Provides generated metadata for the {table.Name} configuration table.");
            code.Line("/// </summary>");
            code.Open($"public static class {table.Name}Table");
            code.Line("// Stores the configured asset path.");
            code.Line($"public const string Path = \"{Escape(table.Path)}\";");
            code.Close();
            code.Close();
            return code.ToString();
        }

        private static void Validate(TableSchema schema)
        {
            if (schema == null)
                throw new ArgumentNullException(nameof(schema));
            GenerationUtility.ValidateNamespace(schema.Namespace, "Table namespace");
            if (schema.Tables == null || schema.Tables.Length == 0)
                throw new InvalidDataException("At least one table definition is required.");

            HashSet<string> names = new(StringComparer.Ordinal);
            for (int i = 0, cnt = schema.Tables.Length; i < cnt; i++)
            {
                var table = schema.Tables[i] ??
                            throw new InvalidDataException($"Table definition {i} is null.");
                GenerationUtility.ValidateIdentifier(table.Name, "Table name");
                if (!names.Add(table.Name))
                    throw new InvalidDataException($"Table '{table.Name}' is defined more than once.");
                if (string.IsNullOrWhiteSpace(table.Path))
                    throw new InvalidDataException($"Table '{table.Name}' requires an asset path.");
                if (table.Fields == null || table.Fields.Length == 0)
                    throw new InvalidDataException($"Table '{table.Name}' requires at least one field.");

                var keyCount = 0;
                HashSet<string> fields = new(StringComparer.Ordinal);
                for (int j = 0, fieldCount = table.Fields.Length; j < fieldCount; j++)
                {
                    var field = table.Fields[j] ??
                                throw new InvalidDataException(
                                    $"Table '{table.Name}' field {j} is null.");
                    GenerationUtility.ValidateIdentifier(field.Name, "Table field");
                    if (!fields.Add(field.Name))
                        throw new InvalidDataException(
                            $"Table '{table.Name}' field '{field.Name}' is duplicated.");
                    if (!sSupportedTypes.Contains(field.Type))
                        throw new InvalidDataException(
                            $"Table '{table.Name}' field '{field.Name}' uses unsupported type '{field.Type}'.");
                    if (field.Key)
                        keyCount++;
                }
                if (keyCount != 1)
                    throw new InvalidDataException(
                        $"Table '{table.Name}' must define exactly one key field.");
            }
        }

        private static TableFieldDefinition GetKeyField(TableDefinition table)
        {
            for (int i = 0, cnt = table.Fields.Length; i < cnt; i++)
            {
                if (table.Fields[i].Key)
                    return table.Fields[i];
            }
            throw new InvalidDataException($"Table '{table.Name}' has no key field.");
        }

        private static bool RemoveStaleFiles(string outputPath, HashSet<string> expectedFiles)
        {
            if (!Directory.Exists(outputPath))
                return false;
            var changed = false;
            var files   = Directory.GetFiles(outputPath, "*Table.Generated.cs");
            for (int i = 0, cnt = files.Length; i < cnt; i++)
            {
                if (expectedFiles.Contains(Path.GetFullPath(files[i])))
                    continue;
                File.Delete(files[i]);
                var metaPath = files[i] + ".meta";
                if (File.Exists(metaPath))
                    File.Delete(metaPath);
                changed = true;
            }
            return changed;
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
