using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using Tritone.Editor.CodeGeneration;
using Tritone.Unity.UI;
using UnityEditor;
using UnityEngine;

namespace Tritone.Editor.UI
{
    /// <summary>
    /// Generates and binds strongly typed UIView components from prefab authoring metadata.
    /// </summary>
    internal static class UIViewCodeGenerator
    {
        /// <summary>
        /// Generates one deterministic UIView source file.
        /// </summary>
        /// <param name="prefabRef">The prefab authoring component.</param>
        /// <returns>True when the source file changed; otherwise, false.</returns>
        internal static bool Generate(UIPrefabRef prefabRef)
        {
            if (!Validate(prefabRef, out var className))
                return false;
            var path    = GetOutputPath(prefabRef, className);
            var changed = GeneratedFileWriter.WriteIfChanged(path, BuildSource(prefabRef, className));
            Debug.Log(changed ? $"Generated UIView: {path}" : $"UIView is current: {path}", prefabRef);
            return changed;
        }

        /// <summary>
        /// Adds the generated UIView component and assigns every generated reference.
        /// </summary>
        /// <param name="prefabRef">The prefab authoring component.</param>
        /// <returns>True when the generated view was found and bound; otherwise, false.</returns>
        internal static bool Bind(UIPrefabRef prefabRef)
        {
            if (!Validate(prefabRef, out var className))
                return false;
            var fullName = prefabRef.Namespace + "." + className;
            var type     = FindViewType(fullName);
            if (type == null)
            {
                Debug.LogError($"Generated UIView type '{fullName}' was not found. Wait for Unity compilation, then bind again.", prefabRef);
                return false;
            }

            var view = prefabRef.GetComponent(type) as UIView;
            if (!view)
                view = Undo.AddComponent(prefabRef.gameObject, type) as UIView;
            if (!view)
                return false;

            Undo.RecordObject(view, "Bind generated UIView");
            foreach (var reference in prefabRef.References)
            {
                var field = type.GetField(reference.Name, BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly);
                if (field == null || !field.FieldType.IsInstanceOfType(reference.Value))
                {
                    Debug.LogError($"UIView field '{reference.Name}' does not match its prefab reference. Regenerate the script.", prefabRef);
                    return false;
                }
                field.SetValue(view, reference.Value);
            }
            view.SortingNodes = prefabRef.SortingNodes;
            EditorUtility.SetDirty(view);
            PrefabUtility.RecordPrefabInstancePropertyModifications(view);
            AssetDatabase.SaveAssets();
            return true;
        }

        /// <summary>
        /// Converts an authoring name into a PascalCase C# identifier.
        /// </summary>
        /// <param name="value">The authoring name.</param>
        /// <returns>The generated identifier.</returns>
        internal static string ToIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "View";
            var builder    = new StringBuilder(value.Length + 1);
            var upperNext  = true;
            foreach (var character in value)
            {
                if (!char.IsLetterOrDigit(character) && character != '_')
                {
                    upperNext = true;
                    continue;
                }
                var next = upperNext ? char.ToUpperInvariant(character) : character;
                if (builder.Length == 0 && char.IsDigit(next))
                    builder.Append('_');
                builder.Append(next);
                upperNext = false;
            }
            return builder.Length == 0 ? "View" : builder.ToString();
        }

        /// <summary>
        /// Builds one generated source without touching the asset database.
        /// </summary>
        /// <param name="prefabRef">The prefab authoring component.</param>
        /// <param name="className">The validated generated class name.</param>
        /// <returns>The complete generated C# source.</returns>
        internal static string BuildSource(UIPrefabRef prefabRef, string className)
        {
            var code = new CodeTextBuilder();
            code.Line("// <auto-generated />");
            code.Line();
            code.Open($"namespace {prefabRef.Namespace}");
            code.Line("/// <summary>");
            code.Line($"/// Provides strongly typed references for the {EscapeXml(prefabRef.name)} prefab.");
            code.Line("/// </summary>");
            code.Open($"public sealed class {className} : global::Tritone.Unity.UI.UIView");
            foreach (var reference in prefabRef.References)
            {
                var description = string.IsNullOrWhiteSpace(reference.Description) ? reference.Name : reference.Description;
                var typeName    = "global::" + reference.Value.GetType().FullName.Replace('+', '.');
                code.Line("/// <summary>");
                code.Line($"/// {EscapeXml(description)}");
                code.Line("/// </summary>");
                code.Line($"public {typeName} {reference.Name};");
                code.Line();
            }
            code.Close();
            code.Close();
            return code.ToString();
        }

        /// <summary>
        /// Validates generation settings and reference uniqueness.
        /// </summary>
        /// <param name="prefabRef">The prefab authoring component.</param>
        /// <param name="className">The resolved class name.</param>
        /// <returns>True when generation can continue; otherwise, false.</returns>
        private static bool Validate(UIPrefabRef prefabRef, out string className)
        {
            className = null;
            if (!prefabRef)
                return false;
            var derivedName = ToIdentifier(prefabRef.name);
            if (!derivedName.EndsWith("View", StringComparison.Ordinal))
                derivedName += "View";
            className = string.IsNullOrWhiteSpace(prefabRef.ClassName) ? derivedName : prefabRef.ClassName;
            try
            {
                GenerationUtility.ValidateIdentifier(className, nameof(UIPrefabRef.ClassName));
                GenerationUtility.ValidateNamespace(prefabRef.Namespace, nameof(UIPrefabRef.Namespace));
            }
            catch (Exception exception)
            {
                Debug.LogError(exception.Message, prefabRef);
                return false;
            }
            if (prefabRef.References == null)
                return true;

            HashSet<string> names = new(StringComparer.Ordinal);
            foreach (var reference in prefabRef.References)
            {
                if (!reference.Value)
                {
                    Debug.LogError($"UIView reference '{reference.Name}' has no value.", prefabRef);
                    return false;
                }
                try
                {
                    GenerationUtility.ValidateIdentifier(reference.Name, "UIView reference");
                }
                catch (Exception exception)
                {
                    Debug.LogError(exception.Message, prefabRef);
                    return false;
                }
                if (!names.Add(reference.Name))
                {
                    Debug.LogError($"UIView reference '{reference.Name}' is duplicated.", prefabRef);
                    return false;
                }
            }
            return true;
        }

        /// <summary>
        /// Resolves and validates the generated output path below the project's Assets directory.
        /// </summary>
        /// <param name="prefabRef">The prefab authoring component.</param>
        /// <param name="className">The generated class name.</param>
        /// <returns>The validated source path.</returns>
        private static string GetOutputPath(UIPrefabRef prefabRef, string className)
        {
            if (string.IsNullOrWhiteSpace(prefabRef.OutputDirectory))
                throw new InvalidOperationException("UIView output directory is required.");
            var projectRoot = Path.GetDirectoryName(Application.dataPath);
            var assetsRoot  = Path.GetFullPath(Application.dataPath) + Path.DirectorySeparatorChar;
            var output      = Path.GetFullPath(Path.Combine(projectRoot, prefabRef.OutputDirectory));
            if (!output.StartsWith(assetsRoot, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("UIView output directory must be below Assets.");
            return Path.Combine(output, className + ".Generated.cs");
        }

        /// <summary>
        /// Finds one generated view type without runtime reflection scans.
        /// </summary>
        /// <param name="fullName">The generated fully qualified type name.</param>
        /// <returns>The matching view type, or null when compilation has not completed.</returns>
        private static Type FindViewType(string fullName)
        {
            foreach (var type in TypeCache.GetTypesDerivedFrom<UIView>())
            {
                if (string.Equals(type.FullName, fullName, StringComparison.Ordinal))
                    return type;
            }
            return null;
        }

        /// <summary>
        /// Escapes text used inside generated XML documentation.
        /// </summary>
        /// <param name="value">The unescaped documentation text.</param>
        /// <returns>The escaped documentation text.</returns>
        private static string EscapeXml(string value)
        {
            return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
