using System;
using System.IO;
using NUnit.Framework;
using Tritone.Editor.CodeGeneration;
using Tritone.Editor.UI;
using Tritone.Unity.UI;
using UnityEngine;
using UnityEngine.UI;

namespace Tritone.Tests
{
    /// <summary>
    /// Verifies deterministic table and network source generation.
    /// </summary>
    public sealed class CodeGenerationTests
    {
        // Stores the isolated generation directory used by each test.
        private string mOutputPath;

        [SetUp]
        public void SetUp()
        {
            mOutputPath = Path.Combine("Temp", "TritoneGenerationTests", Guid.NewGuid().ToString("N"));
        }

        /// <summary>
        /// Verifies that generated UI views use the minimal autogenerated marker and strongly typed fields.
        /// </summary>
        [Test]
        public void UIView_GeneratesStronglyTypedReferences()
        {
            GameObject rootObject   = new("Login", typeof(RectTransform), typeof(UIPrefabRef));
            GameObject buttonObject = new("Confirm", typeof(RectTransform), typeof(Button));
            buttonObject.transform.SetParent(rootObject.transform, false);
            var prefabRef = rootObject.GetComponent<UIPrefabRef>();
            prefabRef.Namespace = "Game.UI";
            prefabRef.References = new[]
            {
                new UIViewReference
                {
                    Name        = "ConfirmButton",
                    Value       = buttonObject.GetComponent<Button>(),
                    Description = "Confirms the login request."
                }
            };

            var source = UIViewCodeGenerator.BuildSource(prefabRef, "LoginView");

            StringAssert.StartsWith("// <auto-generated />", source);
            StringAssert.Contains("public sealed class LoginView : global::Tritone.Unity.UI.UIView", source);
            StringAssert.Contains("public global::UnityEngine.UI.Button ConfirmButton;", source);
            StringAssert.DoesNotContain("Copyright", source);
            UnityEngine.Object.DestroyImmediate(rootObject);
        }

        /// <summary>
        /// Verifies that UI preprocessing records authored order and hierarchy depth deterministically.
        /// </summary>
        [Test]
        public void UIView_PreprocessorRecordsSortingHierarchy()
        {
            GameObject rootObject     = new("SortingPrefab", typeof(RectTransform), typeof(UIPrefabRef));
            GameObject frontObject    = new("Front", typeof(RectTransform), typeof(Canvas));
            GameObject backObject     = new("Back", typeof(SpriteRenderer));
            GameObject nestedObject   = new("Nested", typeof(RectTransform), typeof(Canvas));
            frontObject.transform.SetParent(rootObject.transform, false);
            backObject.transform.SetParent(rootObject.transform, false);
            nestedObject.transform.SetParent(frontObject.transform, false);
            frontObject.GetComponent<Canvas>().sortingOrder  = 10;
            backObject.GetComponent<SpriteRenderer>().sortingOrder = -5;
            nestedObject.GetComponent<Canvas>().sortingOrder = 20;
            var prefabRef = rootObject.GetComponent<UIPrefabRef>();

            Assert.IsTrue(UIViewPreprocessor.Process(prefabRef));

            Assert.AreEqual(3, prefabRef.SortingNodes.Length);
            Assert.AreSame(backObject.GetComponent<SpriteRenderer>(), prefabRef.SortingNodes[0].Target);
            Assert.AreEqual(1, prefabRef.SortingNodes[0].HierarchyDepth);
            Assert.AreSame(frontObject.GetComponent<Canvas>(), prefabRef.SortingNodes[1].Target);
            Assert.AreSame(nestedObject.GetComponent<Canvas>(), prefabRef.SortingNodes[2].Target);
            Assert.AreEqual(2, prefabRef.SortingNodes[2].HierarchyDepth);
            UnityEngine.Object.DestroyImmediate(rootObject);
        }

        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(mOutputPath))
                Directory.Delete(mOutputPath, true);
        }

        [Test]
        public void Tables_GenerateIncrementally()
        {
            TableSchema schema = new()
            {
                Namespace  = "Game.Tables",
                OutputPath = mOutputPath,
                Tables     = new[]
                {
                    new TableDefinition
                    {
                        Name   = "Role",
                        Path   = "Tables/Roles",
                        Fields = new[]
                        {
                            new TableFieldDefinition
                            {
                                Name = "Id",
                                Type = "int",
                                Key  = true
                            },
                            new TableFieldDefinition
                            {
                                Name = "Name",
                                Type = "string"
                            }
                        }
                    }
                }
            };

            Assert.IsTrue(TableCodeGenerator.Generate(schema));
            Assert.IsFalse(TableCodeGenerator.Generate(schema));
            var source = File.ReadAllText(
                Path.Combine(mOutputPath, "RoleTable.Generated.cs"));
            StringAssert.Contains("ITableRow<int>", source);
            StringAssert.Contains("public int Key => Id;", source);
        }

        [Test]
        public void Network_GeneratesRelationshipsCodecsAndRegistry()
        {
            NetworkSchema schema = CreateNetworkSchema();

            Assert.IsTrue(NetworkCodeGenerator.Generate(schema));
            Assert.IsFalse(NetworkCodeGenerator.Generate(schema));
            var source = File.ReadAllText(
                Path.Combine(mOutputPath, "LoginRequestMessage.Generated.cs"));
            StringAssert.Contains("INetworkRequest<LoginResponse>", source);
            StringAssert.Contains("writer.WriteInt32(message.RequestId);", source);
            var registry = File.ReadAllText(
                Path.Combine(mOutputPath, "NetworkMessages.Generated.cs"));
            StringAssert.Contains("LoginRequestId = 1001", registry);
            StringAssert.Contains("serializer.Register", registry);
            StringAssert.Contains("NetworkProtocolDescriptor Protocol", registry);
            StringAssert.Contains("\"game-main\", 2, 3, 1", registry);
        }

        private NetworkSchema CreateNetworkSchema()
        {
            return new NetworkSchema
            {
                ProtocolId          = "game-main",
                MajorVersion        = 2,
                MinorVersion        = 3,
                MinimumMinorVersion = 1,
                Namespace           = "Game.Network",
                OutputPath          = mOutputPath,
                Messages            = new[]
                {
                    new NetworkMessageDefinition
                    {
                        Id       = 1001,
                        Name     = "LoginRequest",
                        Kind     = "Request",
                        Response = "LoginResponse",
                        Fields   = new[]
                        {
                            new NetworkFieldDefinition
                            {
                                Name = "Account",
                                Type = "string"
                            }
                        }
                    },
                    new NetworkMessageDefinition
                    {
                        Id     = 1002,
                        Name   = "LoginResponse",
                        Kind   = "Response",
                        Fields = Array.Empty<NetworkFieldDefinition>()
                    }
                }
            };
        }
    }
}
