using System;
using System.IO;
using NUnit.Framework;
using Tritone.Editor.CodeGeneration;
using Tritone.Editor.UI;
using Tritone.Editor.Tables;
using Tritone.Unity.UI;
using UnityEngine;
using UnityEngine.UI;

namespace Tritone.Tests
{
    /// <summary>
    /// Verifies deterministic table and network source generation.
    /// </summary>
    public sealed class CodeGenerationTests
    {
        // Stores the isolated generation directory used by each test.
        private string mOutputPath;

        [SetUp]
        public void SetUp()
        {
            mOutputPath = Path.Combine("Temp", "TritoneGenerationTests", Guid.NewGuid().ToString("N"));
        }

        /// <summary>
        /// Verifies that generated UI views use the minimal autogenerated marker and strongly typed fields.
        /// </summary>
        [Test]
        public void UIView_GeneratesStronglyTypedReferences()
        {
            GameObject rootObject   = new("Login", typeof(RectTransform), typeof(UIPrefabRef));
            GameObject buttonObject = new("Confirm", typeof(RectTransform), typeof(Button));
            buttonObject.transform.SetParent(rootObject.transform, false);
            var prefabRef = rootObject.GetComponent<UIPrefabRef>();
            prefabRef.Namespace = "Game.UI";
            prefabRef.References = new[]
            {
                new UIViewReference
                {
                    Name        = "ConfirmButton",
                    Value       = buttonObject.GetComponent<Button>(),
                    Description = "Confirms the login request."
                }
            };

            var source = UIViewCodeGenerator.BuildSource(prefabRef, "LoginView");

            StringAssert.StartsWith("// <auto-generated />", source);
            StringAssert.Contains("public sealed class LoginView : global::Tritone.Unity.UI.UIView", source);
            StringAssert.Contains("public global::UnityEngine.UI.Button ConfirmButton;", source);
            StringAssert.DoesNotContain("Copyright", source);
            UnityEngine.Object.DestroyImmediate(rootObject);
        }

        /// <summary>
        /// Verifies that UI preprocessing records authored order and hierarchy depth deterministically.
        /// </summary>
        [Test]
        public void UIView_PreprocessorRecordsSortingHierarchy()
        {
            GameObject rootObject     = new("SortingPrefab", typeof(RectTransform), typeof(UIPrefabRef));
            GameObject frontObject    = new("Front", typeof(RectTransform), typeof(Canvas));
            GameObject backObject     = new("Back", typeof(SpriteRenderer));
            GameObject nestedObject   = new("Nested", typeof(RectTransform), typeof(Canvas));
            frontObject.transform.SetParent(rootObject.transform, false);
            backObject.transform.SetParent(rootObject.transform, false);
            nestedObject.transform.SetParent(frontObject.transform, false);
            frontObject.GetComponent<Canvas>().sortingOrder  = 10;
            backObject.GetComponent<SpriteRenderer>().sortingOrder = -5;
            nestedObject.GetComponent<Canvas>().sortingOrder = 20;
            var prefabRef = rootObject.GetComponent<UIPrefabRef>();

            Assert.IsTrue(UIViewPreprocessor.Process(prefabRef));

            Assert.AreEqual(3, prefabRef.SortingNodes.Length);
            Assert.AreSame(backObject.GetComponent<SpriteRenderer>(), prefabRef.SortingNodes[0].Target);
            Assert.AreEqual(1, prefabRef.SortingNodes[0].HierarchyDepth);
            Assert.AreSame(frontObject.GetComponent<Canvas>(), prefabRef.SortingNodes[1].Target);
            Assert.AreSame(nestedObject.GetComponent<Canvas>(), prefabRef.SortingNodes[2].Target);
            Assert.AreEqual(2, prefabRef.SortingNodes[2].HierarchyDepth);
            UnityEngine.Object.DestroyImmediate(rootObject);
        }

        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(mOutputPath))
                Directory.Delete(mOutputPath, true);
        }

        [Test]
        public void Tables_GenerateIncrementally()
        {
            TableSchema schema = new()
            {
                Namespace  = "Game.Tables",
                OutputPath = mOutputPath,
                Tables     = new[]
                {
                    new TableDefinition
                    {
                        Name   = "Role",
                        Path   = "Tables/Roles",
                        Fields = new[]
                        {
                            new TableFieldDefinition
                            {
                                Name = "Id",
                                Type = "int",
                                Key  = true
                            },
                            new TableFieldDefinition
                            {
                                Name = "Name",
                                Type = "string"
                            }
                        }
                    }
                }
            };

            Assert.IsTrue(TableCodeGenerator.Generate(schema));
            Assert.IsFalse(TableCodeGenerator.Generate(schema));
            var source = File.ReadAllText(
                Path.Combine(mOutputPath, "RoleTable.Generated.cs"));
            StringAssert.Contains("ITableRow<int>", source);
            StringAssert.Contains("public int Key => Id;", source);
        }

        /// <summary>
        /// Verifies that CSV input generates deterministic code and runtime-compatible JSON data.
        /// </summary>
        [Test]
        public void Tables_CompileCsvIntoCodeAndJson()
        {
            var sourcePath = Path.Combine(mOutputPath, "Roles.csv");
            Directory.CreateDirectory(mOutputPath);
            File.WriteAllText(sourcePath, "Id,Name,Enabled\nint,string,bool\n1001,\"Tristin, WYF\",true\n1002,Aigis,false\n");
            var schema = CreateSourceSchema(sourcePath);

            var first  = TableCodeGenerator.Compile(schema);
            var second = TableCodeGenerator.Compile(schema);

            Assert.IsTrue(first.Succeeded);
            Assert.IsTrue(first.Changed);
            Assert.IsTrue(second.Succeeded);
            Assert.IsFalse(second.Changed);
            var code = File.ReadAllText(Path.Combine(mOutputPath, "RoleTable.Generated.cs"));
            StringAssert.Contains("public sealed partial class RoleRow", code);
            var json = File.ReadAllText(Path.Combine(mOutputPath, "Role.json"));
            StringAssert.Contains("\"Name\": \"Tristin, WYF\"", json);
            StringAssert.Contains("\"Enabled\": true", json);
        }

        /// <summary>
        /// Verifies that one invalid table prevents every generated output from being committed.
        /// </summary>
        [Test]
        public void Tables_ValidationFailureCommitsNoOutputs()
        {
            var sourcePath = Path.Combine(mOutputPath, "Roles.tsv");
            Directory.CreateDirectory(mOutputPath);
            File.WriteAllText(sourcePath, "Id\tName\tEnabled\nint\tstring\tbool\n1001\tFirst\ttrue\n1001\tSecond\tfalse\n");
            var schema = CreateSourceSchema(sourcePath);

            var result = TableCodeGenerator.Compile(schema);

            Assert.IsFalse(result.Succeeded);
            Assert.IsFalse(result.Changed);
            Assert.IsTrue(ContainsDiagnostic(result.Diagnostics, "TRT-TABLE-3102"));
            Assert.IsFalse(File.Exists(Path.Combine(mOutputPath, "RoleTable.Generated.cs")));
            Assert.IsFalse(File.Exists(Path.Combine(mOutputPath, "Role.json")));
        }

        [Test]
        public void Network_GeneratesRelationshipsCodecsAndRegistry()
        {
            NetworkSchema schema = CreateNetworkSchema();

            Assert.IsTrue(NetworkCodeGenerator.Generate(schema));
            Assert.IsFalse(NetworkCodeGenerator.Generate(schema));
            var source = File.ReadAllText(
                Path.Combine(mOutputPath, "LoginRequestMessage.Generated.cs"));
            StringAssert.Contains("INetworkRequest<LoginResponse>", source);
            StringAssert.Contains("writer.WriteInt32(message.RequestId);", source);
            var registry = File.ReadAllText(
                Path.Combine(mOutputPath, "NetworkMessages.Generated.cs"));
            StringAssert.Contains("LoginRequestId = 1001", registry);
            StringAssert.Contains("serializer.Register", registry);
            StringAssert.Contains("NetworkProtocolDescriptor Protocol", registry);
            StringAssert.Contains("\"game-main\", 2, 3, 1", registry);
        }

        private NetworkSchema CreateNetworkSchema()
        {
            return new NetworkSchema
            {
                ProtocolId          = "game-main",
                MajorVersion        = 2,
                MinorVersion        = 3,
                MinimumMinorVersion = 1,
                Namespace           = "Game.Network",
                OutputPath          = mOutputPath,
                Messages            = new[]
                {
                    new NetworkMessageDefinition
                    {
                        Id       = 1001,
                        Name     = "LoginRequest",
                        Kind     = "Request",
                        Response = "LoginResponse",
                        Fields   = new[]
                        {
                            new NetworkFieldDefinition
                            {
                                Name = "Account",
                                Type = "string"
                            }
                        }
                    },
                    new NetworkMessageDefinition
                    {
                        Id     = 1002,
                        Name   = "LoginResponse",
                        Kind   = "Response",
                        Fields = Array.Empty<NetworkFieldDefinition>()
                    }
                }
            };
        }

        /// <summary>
        /// Creates one source-backed table schema using the isolated test directory.
        /// </summary>
        /// <param name="sourcePath">The CSV or TSV source path.</param>
        /// <returns>The configured schema.</returns>
        private TableSchema CreateSourceSchema(string sourcePath)
        {
            return new TableSchema
            {
                Namespace      = "Game.Tables",
                OutputPath    = mOutputPath,
                DataOutputPath = mOutputPath,
                Tables        = new[]
                {
                    new TableDefinition
                    {
                        Name     = "Role",
                        Path     = "Tables/Role",
                        Source   = sourcePath,
                        DataFile = "Role.json"
                    }
                }
            };
        }

        /// <summary>
        /// Checks whether a build result contains one stable diagnostic code.
        /// </summary>
        /// <param name="diagnostics">The build diagnostics.</param>
        /// <param name="code">The diagnostic code.</param>
        /// <returns>True when the code exists.</returns>
        private static bool ContainsDiagnostic(TableDiagnostic[] diagnostics, string code)
        {
            foreach (var diagnostic in diagnostics)
            {
                if (diagnostic.Code == code)
                {
                    return true;
                }
            }
            return false;
        }
    }
}
