using System;
using System.IO;
using Tritone.Editor.CodeGeneration;

namespace Tritone.Editor.Tables
{
    /// <summary>
    /// Generates minimal partial row and descriptor types for the existing Tritone runtime.
    /// </summary>
    public sealed class CSharpTableCodeGenerator : ITableCodeGenerator
    {
        /// <inheritdoc />
        public TableGeneratedFile Generate(TableSchema schema, TableDefinition table, ITableFieldType[] fieldTypes)
        {
            var keyIndex  = GetKeyIndex(table);
            var keyField  = table.Fields[keyIndex];
            var output    = string.IsNullOrWhiteSpace(schema.OutputPath) ? "Assets/Generated/Tritone/Tables" : schema.OutputPath;
            var code      = new CodeTextBuilder();
            code.Line("// <auto-generated />");
            code.Line("using System;");
            code.Line("using Tritone.Tables;");
            code.Line();
            code.Open($"namespace {schema.Namespace}");
            code.Line("/// <summary>");
            code.Line($"/// Stores one row from the {table.Name} configuration table.");
            code.Line("/// </summary>");
            code.Line("[Serializable]");
            code.Open($"public sealed partial class {table.Name}Row : ITableRow<{fieldTypes[keyIndex].CSharpTypeName}>");
            for (var i = 0; i < table.Fields.Length; i++)
            {
                var field       = table.Fields[i];
                var description = string.IsNullOrWhiteSpace(field.Description) ? $"Stores the {field.Name} configuration value." : EscapeXml(field.Description);
                code.Line("/// <summary>");
                code.Line($"/// {description}");
                code.Line("/// </summary>");
                code.Line($"public {fieldTypes[i].CSharpTypeName} {field.Name};");
                code.Line();
            }
            code.Line("/// <summary>Gets the stable row key.</summary>");
            code.Line($"public {fieldTypes[keyIndex].CSharpTypeName} Key => {keyField.Name};");
            code.Close();
            code.Line();
            code.Line("/// <summary>");
            code.Line($"/// Provides generated metadata for the {table.Name} configuration table.");
            code.Line("/// </summary>");
            code.Open($"public static partial class {table.Name}Table");
            code.Line("/// <summary>Stores the configured runtime asset path.</summary>");
            code.Line($"public const string Path = \"{EscapeString(table.Path)}\";");
            code.Close();
            code.Close();
            return new TableGeneratedFile(Path.Combine(output, table.Name + "Table.Generated.cs"), code.ToString());
        }

        /// <summary>Gets the required key field index.</summary>
        /// <param name="table">The validated table definition.</param>
        /// <returns>The key field index.</returns>
        private static int GetKeyIndex(TableDefinition table)
        {
            for (var i = 0; i < table.Fields.Length; i++)
            {
                if (table.Fields[i].Key)
                {
                    return i;
                }
            }
            throw new InvalidOperationException($"Table '{table.Name}' has no key field.");
        }

        /// <summary>Escapes one generated string literal.</summary>
        /// <param name="value">The unescaped value.</param>
        /// <returns>The escaped value.</returns>
        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        /// <summary>Escapes generated XML documentation.</summary>
        /// <param name="value">The unescaped text.</param>
        /// <returns>The escaped text.</returns>
        private static string EscapeXml(string value)
        {
            return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
    }
}
